version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_short_app
    restart: always
    ports:
      - "9080:8080"
    depends_on:
      - postgres
    networks:
      - go_short_network

  postgres:
    image: postgres:14-alpine
    container_name: go_short_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_short
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go_short_network

networks:
  go_short_network:
    driver: bridge

volumes:
  postgres_data:
